contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #longtrench channel"
    url: https://nfcore.slack.com/channels/longtrench
    about: Discussion about the nf-core/longtrench pipeline
